### ISSUE TITLE
Documentation not up-to-date?

### ISSUE THREAD

**Issue by henry2004y** [JuliaVlasov/VlasovSolvers.jl#2]
Hello,

I enjoy going through the documentation of this package and really appreciate your work here!

When I was trying to run the [two-stream example](https://juliavlasov.github.io/VlasovSolvers.jl/dev/tsi/), I found that the section for importing package was missing in the documentation while it is present in the [source code](https://github.com/JuliaVlasov/VlasovSolvers.jl/blob/master/docs/src/tsi.md). Is it possible that the documents are not updated to the latest version?

**Comment by pnavaro** [comment]
The gif animation should be here, i will take a look.

**Comment by pnavaro** [comment]
Dear @henry2004y, thanks for your comments i fixed the example.
This code is not really a package, it is just some samples in order to define a good interface. The  package will be
https://github.com/juliavlasov/SemiLagrangian.jl but it is still an ongoing work though.

**Comment by henry2004y** [comment]
Thanks for the quick fix! Maybe I will come back later with other questions as I go through the examples and codes.

**Comment by henry2004y** [comment]
Hi again,

I found some similar issues in other doc pages as well: [vlasov-poisson](https://juliavlasov.github.io/VlasovSolvers.jl/dev/vlasov-poisson/), [rotation2d](https://juliavlasov.github.io/VlasovSolvers.jl/dev/rotation2d/), [Vlasov-HMF](https://juliavlasov.github.io/VlasovSolvers.jl/dev/vlasov-hmf/).

**Comment by pnavaro** [comment]
Package imports are just hidden in the example setup, i can make it visible.
