### ISSUE TITLE
Confusion in the description of B-Spline interpolation

### ISSUE THREAD

**Issue by henry2004y** [JuliaVlasov/VlasovSolvers.jl#5]
Hello,

I was confused by the notations the first time I read the documentation on [B-Spline](https://juliavlasov.github.io/VlasovSolvers.jl/dev/#Semi-Lagrangian-method). When I read more about this, I realized that traditionally `t_i` are used to denote knots of the B-Spline curves, which happens to share the same letter with time in the vlasov equation. Is it the case here?

I don't know what is a better way to distinguish these two. Maybe here we need to replace knots with some other letter.

**Comment by pnavaro** [comment]
t here means tau so we can replace it by \tau

**Comment by pnavaro** [comment]
Salut Nico

Le wolferine est en train de revoir tout les codes de VlasovSolvers. On en discute si tu veux voir comment on fonctionne sur GitHub pour les contributions 

Pierre

Envoyé de mon iPhone

**Comment by pnavaro** [comment]
Sorry I made an answer in French to my colleague. @crouseilles .he will take a look to improve the doc.

**Comment by pnavaro** [comment]
Dear @henry2004y , thanks for your comment and your contribution. Are you interested to be part of the project. I have a colleague that works on Semi-Lagrangian and i am focused myself on the Particle-In-Cell.
You could contribute to this repo without using PR.
Keep in touch, cheers. Pierre.

**Comment by henry2004y** [comment]
Thank you too! I am interested to be part of the project. I come from the MHD and PIC world, and now I am interested in exploring the Vlasov solvers. I see that the Semi-Lagrangian package is under dev, and it would be an honor for me to see what I can contribute to the package. Most of the current existing Vlasov solvers for research that I am aware of are in either written 
in Fortran, C or C++; with the recent rapid development of Julia, I want to see if Julia is capable of competing with others in the HPC world.

Thanks again for the invitation on collaboration @pnavaro. I would like to join and work in my free time, and I will try to follow the guidance.
